### ISSUE TITLE
Doesn't work on monogame 3.5

### ISSUE THREAD

**Issue by fxgenstudio** [tgjones/monogame-samples#1]
An unhandled exception of type 'System.InvalidOperationException' occurred in MonoGame.Framework.dll

Additional information: An error occurred while preparing to draw. This is probably because the current vertex declaration does not include all the elements required by the current vertex shader. The current vertex declaration includes these elements: SV_Position0, NORMAL0, TEXCOORD0.

**Comment by fxgenstudio** [comment]
In Mesh.fx you need change:

struct VSInput
{
    float3 PositionOS : SV_POSITION;
    float3 Color      : COLOR;
    float3 NormalOS   : NORMAL;
};

to

struct VSInput
{
    float3 PositionOS : SV_POSITION;
    float3 NormalOS   : NORMAL;
        float2 Texture    : TEXCOORD0;
};

**Comment by tgjones** [comment]
Thanks!
