### ISSUE TITLE
don't work in monogame 3.6 version

### ISSUE THREAD

**Issue by nerogcy** [tgjones/monogame-samples#2]
cant see any shadow in 3.6
![image](https://cloud.githubusercontent.com/assets/20985725/25846217/8da15e44-34e3-11e7-965b-09d7d8ef369b.png)

**Comment by tgjones** [comment]
Hmm, it's been a while since I last worked with MonoGame. I'd gladly accept a pull request, if you're able to find out why it's not working, but I don't have time to investigate this myself.

**Comment by nerogcy** [comment]
i spent quite lot of time on it, but still cant figure out wat is the problem. can you help?

**Comment by Kosmonaut3d** [comment]
it looks like the SamplerComparisonState was not initialized correctly/ not working correctly, which is a general problem with samplers in monogame right now.

All of this is in the Mesh.fx

An easy fix is to change the SamplerComparisonState to a SamplerState like so

SamplerState ShadowSampler : register(s0);

and make manual comparisons instead, so replace 
Ln 81
**return ShadowMap.SampleCmpLevelZero(ShadowSampler, float3(shadowPos.xy, cascadeIdx), lightDepth);**
with
**return ShadowMap.SampleLevel(ShadowSampler, float3(uv, cascadeIdx), 0) > z;**

Ln 116 
        **return ShadowMap.SampleCmpLevelZero(ShadowSampler, float3(shadowPos.xy, cascadeIdx), lightDepth);**
with
**return ShadowMap.SampleLevel(ShadowSampler, float3(shadowPos.xy, cascadeIdx), 0) > lightDepth;**

**Comment by tgjones** [comment]
@Kosmonaut3d thanks for that. I did implement SamplerComparisonState in MonoGame, but either my pull request wasn't merged (I thought it was) or it's been broken since then.

**Comment by tgjones** [comment]
Fixed by #3.
